In [1]:
pwd

'C:\\Users\\dell'

In [6]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
data=pd.read_csv('values.csv') 
print(data)

    patient_id  slope_of_peak_exercise_st_segment               thal  \
0       0z64un                                  1             normal
1       ryoo3j                                  2             normal
2       yt1s1x                                  1             normal
3       l2xjde                                  1  reversible_defect
4       oyt4ek                                  3  reversible_defect
..         ...                                ...                ...
175     5qfar3                                  2  reversible_defect
176     2s2b1f                                  2             normal
177     nsd00i                                  2  reversible_defect
178     0xw93k                                  1             normal
179     2nx10r                                  1             normal

     resting_blood_pressure  chest_pain_type  num_major_vessels  \
0                       128                2                  0
1                       110                3                  0
2                       125                4                  3
3                       152                4                  0
4                       178                1                  0
..                      ...              ...                ...
175                     125                4                  2
176                     180                4                  0
177                     125                3                  0
178                     124                3                  2
179                     160                3                  1

     fasting_blood_sugar_gt_120_mg_per_dl  resting_ekg_results  \
0                                       0                    2
1                                       0                    0
2                                       0                    2
3                                       0                    0
4                                       0                    2
..                                    ...                  ...
175                                     1                    0
176                                     0                    1
177                                     0                    0
178                                     1                    0
179                                     0                    0

     serum_cholesterol_mg_per_dl  oldpeak_eq_st_depression  sex  age  \
0                            308                       0.0    1   45
1                            214                       1.6    0   54
2                            304                       0.0    1   77
3                            223                       0.0    1   40
4                            270                       4.2    1   59
..                           ...                       ...  ...  ...
175                          254                       0.2    1   67
176                          327                       3.4    0   55
177                          309                       1.8    1   64
178                          255                       0.0    1   48
179                          201                       0.0    0   54

     max_heart_rate_achieved  exercise_induced_angina
0                        170                        0
1                        158                        0
2                        162                        1
3                        181                        0
4                        145                        0
..                       ...                      ...
175                      163                        0
176                      117                        1
177                      131                        1
178                      175                        0
179                      163                        0

[180 rows x 14 columns]

In [5]:
data.head()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
0,0z64un,1,normal,128,2,0,0,2,308,0.0,1,45,170,0
1,ryoo3j,2,normal,110,3,0,0,0,214,1.6,0,54,158,0
2,yt1s1x,1,normal,125,4,3,0,2,304,0.0,1,77,162,1
3,l2xjde,1,reversible_defect,152,4,0,0,0,223,0.0,1,40,181,0
4,oyt4ek,3,reversible_defect,178,1,0,0,2,270,4.2,1,59,145,0

In [24]:
data.tail()

,patient_id,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
175,5qfar3,2,reversible_defect,125,4,2,1,0,254,0.2,1,67,163,0
176,2s2b1f,2,normal,180,4,0,0,1,327,3.4,0,55,117,1
177,nsd00i,2,reversible_defect,125,3,0,0,0,309,1.8,1,64,131,1
178,0xw93k,1,normal,124,3,2,1,0,255,0.0,1,48,175,0
179,2nx10r,1,normal,160,3,1,0,0,201,0.0,0,54,163,0

In [8]:
data=data.drop('patient_id',axis=1)
print("\nDataframe after dropping 'patient_id'column:")
print(data)

Dataframe after dropping 'patient_id'column:
     slope_of_peak_exercise_st_segment               thal  \
0                                    1             normal
1                                    2             normal
2                                    1             normal
3                                    1  reversible_defect
4                                    3  reversible_defect
..                                 ...                ...
175                                  2  reversible_defect
176                                  2             normal
177                                  2  reversible_defect
178                                  1             normal
179                                  1             normal

     resting_blood_pressure  chest_pain_type  num_major_vessels  \
0                       128                2                  0
1                       110                3                  0
2                       125                4                  3
3                       152                4                  0
4                       178                1                  0
..                      ...              ...                ...
175                     125                4                  2
176                     180                4                  0
177                     125                3                  0
178                     124                3                  2
179                     160                3                  1

     fasting_blood_sugar_gt_120_mg_per_dl  resting_ekg_results  \
0                                       0                    2
1                                       0                    0
2                                       0                    2
3                                       0                    0
4                                       0                    2
..                                    ...                  ...
175                                     1                    0
176                                     0                    1
177                                     0                    0
178                                     1                    0
179                                     0                    0

     serum_cholesterol_mg_per_dl  oldpeak_eq_st_depression  sex  age  \
0                            308                       0.0    1   45
1                            214                       1.6    0   54
2                            304                       0.0    1   77
3                            223                       0.0    1   40
4                            270                       4.2    1   59
..                           ...                       ...  ...  ...
175                          254                       0.2    1   67
176                          327                       3.4    0   55
177                          309                       1.8    1   64
178                          255                       0.0    1   48
179                          201                       0.0    0   54

     max_heart_rate_achieved  exercise_induced_angina
0                        170                        0
1                        158                        0
2                        162                        1
3                        181                        0
4                        145                        0
..                       ...                      ...
175                      163                        0
176                      117                        1
177                      131                        1
178                      175                        0
179                      163                        0

[180 rows x 13 columns]

In [9]:
data=data.drop('thal',axis=1)
print("\nDataframe after dropping 'thal'column:")
print(data)

Dataframe after dropping 'thal'column:
     slope_of_peak_exercise_st_segment  resting_blood_pressure  \
0                                    1                     128
1                                    2                     110
2                                    1                     125
3                                    1                     152
4                                    3                     178
..                                 ...                     ...
175                                  2                     125
176                                  2                     180
177                                  2                     125
178                                  1                     124
179                                  1                     160

     chest_pain_type  num_major_vessels  fasting_blood_sugar_gt_120_mg_per_dl  \
0                  2                  0                                     0
1                  3                  0                                     0
2                  4                  3                                     0
3                  4                  0                                     0
4                  1                  0                                     0
..               ...                ...                                   ...
175                4                  2                                     1
176                4                  0                                     0
177                3                  0                                     0
178                3                  2                                     1
179                3                  1                                     0

     resting_ekg_results  serum_cholesterol_mg_per_dl  \
0                      2                          308
1                      0                          214
2                      2                          304
3                      0                          223
4                      2                          270
..                   ...                          ...
175                    0                          254
176                    1                          327
177                    0                          309
178                    0                          255
179                    0                          201

     oldpeak_eq_st_depression  sex  age  max_heart_rate_achieved  \
0                         0.0    1   45                      170
1                         1.6    0   54                      158
2                         0.0    1   77                      162
3                         0.0    1   40                      181
4                         4.2    1   59                      145
..                        ...  ...  ...                      ...
175                       0.2    1   67                      163
176                       3.4    0   55                      117
177                       1.8    1   64                      131
178                       0.0    1   48                      175
179                       0.0    0   54                      163

     exercise_induced_angina
0                          0
1                          0
2                          1
3                          0
4                          0
..                       ...
175                        0
176                        1
177                        1
178                        0
179                        0

[180 rows x 12 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 12 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   slope_of_peak_exercise_st_segment     180 non-null    int64
 1   resting_blood_pressure                180 non-null    int64
 2   chest_pain_type                       180 non-null    int64
 3   num_major_vessels                     180 non-null    int64
 4   fasting_blood_sugar_gt_120_mg_per_dl  180 non-null    int64
 5   resting_ekg_results                   180 non-null    int64
 6   serum_cholesterol_mg_per_dl           180 non-null    int64
 7   oldpeak_eq_st_depression              180 non-null    float64
 8   sex                                   180 non-null    int64
 9   age                                   180 non-null    int64
 10  max_heart_rate_achieved               180 non-null    int64
 11  exercise_induced_angina               180 non-null    int64
dtypes: float64(1), int64(11)
memory usage: 17.0 KB

In [11]:
data.describe()

,slope_of_peak_exercise_st_segment,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina
count,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000
mean,1.550000,131.311111,3.155556,0.694444,0.161111,1.050000,249.211111,1.010000,0.688889,54.811111,149.483333,0.316667
std,0.618838,17.010443,0.938454,0.969347,0.368659,0.998742,52.717969,1.121357,0.464239,9.334737,22.063513,0.466474
min,1.000000,94.000000,1.000000,0.000000,0.000000,0.000000,126.000000,0.000000,0.000000,29.000000,96.000000,0.000000
25%,1.000000,120.000000,3.000000,0.000000,0.000000,0.000000,213.750000,0.000000,0.000000,48.000000,132.000000,0.000000
50%,1.000000,130.000000,3.000000,0.000000,0.000000,2.000000,245.500000,0.800000,1.000000,55.000000,152.000000,0.000000
75%,2.000000,140.000000,4.000000,1.000000,0.000000,2.000000,281.250000,1.600000,1.000000,62.000000,166.250000,1.000000
max,3.000000,180.000000,4.000000,3.000000,1.000000,2.000000,564.000000,6.200000,1.000000,77.000000,202.000000,1.000000

In [13]:
data.shape

(180, 12)

In [14]:
data.isnull().sum()

slope_of_peak_exercise_st_segment       0
resting_blood_pressure                  0
chest_pain_type                         0
num_major_vessels                       0
fasting_blood_sugar_gt_120_mg_per_dl    0
resting_ekg_results                     0
serum_cholesterol_mg_per_dl             0
oldpeak_eq_st_depression                0
sex                                     0
age                                     0
max_heart_rate_achieved                 0
exercise_induced_angina                 0
dtype: int64

In [17]:
data['exercise_induced_angina'].value_counts()

exercise_induced_angina
0    123
1     57
Name: count, dtype: int64

In [19]:
X=data.drop(columns='exercise_induced_angina',axis=1)
Y=data['exercise_induced_angina']
print(X)

     slope_of_peak_exercise_st_segment  resting_blood_pressure  \
0                                    1                     128
1                                    2                     110
2                                    1                     125
3                                    1                     152
4                                    3                     178
..                                 ...                     ...
175                                  2                     125
176                                  2                     180
177                                  2                     125
178                                  1                     124
179                                  1                     160

     chest_pain_type  num_major_vessels  fasting_blood_sugar_gt_120_mg_per_dl  \
0                  2                  0                                     0
1                  3                  0                                     0
2                  4                  3                                     0
3                  4                  0                                     0
4                  1                  0                                     0
..               ...                ...                                   ...
175                4                  2                                     1
176                4                  0                                     0
177                3                  0                                     0
178                3                  2                                     1
179                3                  1                                     0

     resting_ekg_results  serum_cholesterol_mg_per_dl  \
0                      2                          308
1                      0                          214
2                      2                          304
3                      0                          223
4                      2                          270
..                   ...                          ...
175                    0                          254
176                    1                          327
177                    0                          309
178                    0                          255
179                    0                          201

     oldpeak_eq_st_depression  sex  age  max_heart_rate_achieved
0                         0.0    1   45                      170
1                         1.6    0   54                      158
2                         0.0    1   77                      162
3                         0.0    1   40                      181
4                         4.2    1   59                      145
..                        ...  ...  ...                      ...
175                       0.2    1   67                      163
176                       3.4    0   55                      117
177                       1.8    1   64                      131
178                       0.0    1   48                      175
179                       0.0    0   54                      163

[180 rows x 11 columns]

In [20]:
print(Y)

0      0
1      0
2      1
3      0
4      0
      ..
175    0
176    1
177    1
178    0
179    0
Name: exercise_induced_angina, Length: 180, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [32]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)
print(X.shape,X_train.shape,X_test.shape)

(180, 11) (144, 11) (36, 11)

In [33]:
model=LogisticRegression()

In [34]:
model.fit(X_train,Y_train)

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [35]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)
print('Accuracy on Training data:',training_data_accuracy)

Accuracy on Training data: 0.8125

In [36]:
X_test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction,Y_test)
print('Accuracy on Test data:',test_data_accuracy)

Accuracy on Test data: 0.8055555555555556

In [41]:
input_data=(2,150,4,2,0,2,258,2.6,0,60,157)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)

[0]

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [42]:
if (prediction[0]==0):
    print('The person does not have a heart disease')
else:
    print('The person has heart disease')

The person does not have a heart disease